### ISSUE TITLE
web interface to select multiple data bases

### ISSUE THREAD

**Issue by 2sn** [2sn/starfit-server#15]
These should be a selected from the list of available databases, e.g., list with multiple selection or checkboxes.

Passed to `starfit` as tuple.  (a future version as of this writing but temporary adjustment of `starfit` to ignore extra DBs is trivial in case this feature is implemented on the server first)

**Comment by dliptai** [comment]
(Linked to https://github.com/conradtchan/starfit/issues/41)

**Comment by 2sn** [comment]
The `starfit` package now has this capability in https://github.com/conradtchan/starfit/pull/59, but web interface is missing (along with a few option, `cover` for GA and `partition` for Double/Multi.  That is, there should be a general `Multi` rather than `Double`.

**Comment by 2sn** [comment]
what is needed is 
* replace `Double` by `Multi` (in StarFit `0.8.0` `Double` is just an alias for `Multi` with pre-set `sol_size=2`)
* allow selection of multiple DBs for all cases
* for `Ga` add `cover` (True|False) - check box
* for `Multi` add `partition` (True|False) - check box

**Comment by 2sn** [comment]
This has now been implemented
