### ISSUE TITLE
StarFit version

### ISSUE THREAD

**Issue by 2sn** [2sn/starfit-server#5]
It may be useful to display the starfit version used on the server

**Comment by dliptai** [comment]
i'll implement a __version__ in the starfit package

**Comment by dliptai** [comment]
Added in 1b0731af6f9e0836f272073a17a4cd32a5e1c8cd

Note that it won't show a useful version until https://github.com/conradtchan/starfit/pull/34 is released+deployed to the server

**Comment by 2sn** [comment]
with pre-release (`dev`) of `starfit` only showing up as `0.0.0` (https://github.com/conradtchan/starfit/issues/55), the Deployment info should probably also include the git hash of the `starfit` version. (I had issues with outdated pre-release and was not sure what was running for a test situation.)

**Comment by 2sn** [comment]
This seems solved adequately.
